### ISSUE TITLE
Issues with the windows version of the wallet (0.1.2)

### ISSUE THREAD

**Issue by schierlm** [iotaledger/cli-wallet#25]
## Bug description

When creating the wallet, the app offers to create an `.env` file. This file is following Unix conventions - usually the file is called `.env.cmd` on Windows and it needs a `SET ...` command so that it actually sets the variable for the calling cmd window.

When trying to backup the database, the app panicks:

```
C:\PortableApps\iota-wallet-chrysalis>wallet-windows.exe backup newpath0
Backup stored at "newpath0"
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Unable to access snapshot. Make sure that it exists or run encrypt to build a new one.

Caused by:
    Das System kann die angegebene Datei nicht finden. (os error 2)', C:\Users\runneradmin\.cargo\git\checkouts\stronghold.rs-fe28308a6634692d\54638a8\stronghold\src\lib.rs:162:51
stack backtrace:
   0:     0x7ff64b94c3d6 - <unknown>
   1:     0x7ff64b5bd83b - <unknown>
   2:     0x7ff64b94b158 - <unknown>
   3:     0x7ff64b94a498 - <unknown>
   4:     0x7ff64b951bc5 - <unknown>
   5:     0x7ff64b951b87 - <unknown>
   6:     0x7ff64b951b2f - <unknown>
   7:     0x7ff64b5bae50 - <unknown>
   8:     0x7ff64b5bea33 - <unknown>
   9:     0x7ff64b464cf6 - <unknown>
  10:     0x7ff64b503551 - <unknown>
  11:     0x7ff64b51634e - <unknown>
  12:     0x7ff64b486e26 - <unknown>
  13:     0x7ff64b516537 - <unknown>
  14:     0x7ff64bcfa240 - <unknown>
  15:     0x7ffa57027034 - BaseThreadInitThunk
  16:     0x7ffa573dd0d1 - RtlUserThreadStart
```

Also, I am still unsure whether only backing up my mnemonic phrase is sufficient, since when I ran it again in a different directory with the same seed phrase and node, it did not create the same addresses. Poking inside the SQLIte database, however, did not reveal any obvious other secret or nonce inside the JSON data stored there.

## Rust version

Whichever one is bundled in the Windows release https://github.com/iotaledger/cli-wallet/releases/tag/app-v0.1.2 (how do I tell?)

- Rust version:

## Version

0.1.2

## Hardware specification

- Operating system: Windows 10
- RAM: 12 GB
- Cores: 2 (4 with Hyperthreading) Intel(R) Core(TM) i3-3110M CPU @ 2.40GHz   2.40 GHz
- Device: Lenovo L530 notebook

## Steps To reproduce the bug

1. Download the prebuilt windows app and start creating a wallet.
2. Try to use the .env file, curse and fix it manually
3. Try to create a backup

## Expected behaviour

Getting a .env file that can be used out of the box. Be able to create a backup.

## Actual behaviour

The .env file complains about "bad command and file name" after renaming. And backup cannot be created.

**Comment by lucasfernog** [comment]
The `.env` file is loaded by the CLI itself (uses https://github.com/apiraino/rust-dotenv) so it wouldn't need to follow the Windows format.

The backup is indeed buggy and i'm refactoring the wallet library so it can work on this scenario.

And I couldn't reproduce the issue regarding different addresses with same mnemonic, can you detail the steps you did to make it happen?

**Comment by schierlm** [comment]
Thanks for the feedback about the `.env` files - I assumed I had to source it myself.

Indeed I cannot reroduce the different addresses issue when I use the `.env` file:

```
X:\>md 1

X:\>copy wallet-windows.exe 1
        1 Datei(en) kopiert.

X:\>cd 1

X:\1>dir

15.12.2020  16:02        12.485.120 wallet-windows.exe

X:\1>wallet-windows new --node https://api.lb-0.testnet.chrysalis2.com/
Your mnemonic is `wheat stomach valley journey drum dragon inquiry love hurdle embrace digital height famous issue apple sample observe steel hockey door leader morning panda siren`, you must store it on an environment variable called `IOTA_WALLET_MNEMONIC` to use this CLI
Do you want to store the mnemonic in a .env file? yes
mnemonic added to "X:\\1\\.env"
Created account `Account 0`
Account `Account 0` command (h for help): address
ADDRESS "iot1qxs5cg8qdtpr79kap370afqhlma8zhzfeut4l6gw9uzpjstguvrx5ul28rp"
--- Balance: 0
--- Index: 0
--- Change address: false
Account `Account 0` command (h for help): exit

X:\1>cd ..

X:\>md 2

X:\>copy 1\wallet-windows.exe 1\.env 2
Syntaxfehler.

X:\>copy 1\wallet-windows.exe 2
        1 Datei(en) kopiert.

X:\>copy 1\.env 2
        1 Datei(en) kopiert.

X:\>cd 2

X:\2>wallet-windows new --node https://api.lb-0.testnet.chrysalis2.com/
loaded dotenv from "X:\\2\\.env"
Created account `Account 0`
Account `Account 0` command (h for help): address
ADDRESS "iot1qxs5cg8qdtpr79kap370afqhlma8zhzfeut4l6gw9uzpjstguvrx5ul28rp"
--- Balance: 0
--- Index: 0
--- Change address: false
Account `Account 0` command (h for help): exit

X:\2>cd ..

``` 

When instead using the mnemonic in an environment variable, I get different (but consistent) addresses:

```
X:\>mkdir 3

X:\>copy 1\wallet-windows.exe 3
        1 Datei(en) kopiert.

X:\>cd 3

X:\3>set IOTA_WALLET_MNEMONIC="wheat stomach valley journey drum dragon inquiry love hurdle embrace digital height famous issue apple sample observe steel hockey door leader morning panda siren"

X:\3>wallet-windows new --node https://api.lb-0.testnet.chrysalis2.com/
Created account `Account 0`
Account `Account 0` command (h for help): address
ADDRESS "iot1qy825dxthlm0sy5m3ees8xdqj2h3ykulw5ayv74h0j6022mptcunwtrzk7q"
--- Balance: 0
--- Index: 0
--- Change address: false
Account `Account 0` command (h for help): exit

X:\3>cd ..

X:\>md 4

X:\>copy 3\wallet-windows.exe 4
        1 Datei(en) kopiert.

X:\>cd 4

X:\4>wallet-windows new --node https://api.lb-0.testnet.chrysalis2.com/
Created account `Account 0`
Account `Account 0` command (h for help): address
ADDRESS "iot1qy825dxthlm0sy5m3ees8xdqj2h3ykulw5ayv74h0j6022mptcunwtrzk7q"
--- Balance: 0
--- Index: 0
--- Change address: false
Account `Account 0` command (h for help): exit

X:\4>
```

So in fact the difference occured as I created the first address on first start (creating my mnemonic), and after crash scenario simulation I created the address while loading the mnemonic from the environment variable.

It may be an interesting test whether I would be able to spend my balance after having switched the "format". Perhaps will test this later (last time I tried the faucet was not working).

**Comment by schierlm** [comment]
More testing: when I set the value without quotes

```
set IOTA_WALLET_MNEMONIC=wheat stomach valley journey drum dragon inquiry love hurdle embrace digital height famous issue apple sample observe steel hockey door leader morning panda siren
```

I get the correct hashes back. Which makes me think that some mnemonic validation is missing?

In fact, when I replace the *ste**e**l* by *ste**a**l* in the mnemonic, it will still load fine, yet show different addresses. this despite *steal* is not on the BIP39 English wordlist (only steel and steak are).

**Comment by schierlm** [comment]
Another thing, when I press the <kbd>Ctrl</kbd> key on an interactive prompt, I get this:

```
Account `Account 0` command (h for help): thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Custom { kind: NotConnected, error: "Not a terminal" }', src\account.rs:219:10
stack backtrace:
   0:     0x7ff6f493c3d6 - <unknown>
   1:     0x7ff6f45ad83b - <unknown>
   2:     0x7ff6f493b158 - <unknown>
   3:     0x7ff6f493a498 - <unknown>
   4:     0x7ff6f4941bc5 - <unknown>
   5:     0x7ff6f4941b87 - <unknown>
   6:     0x7ff6f4941b2f - <unknown>
   7:     0x7ff6f45aae50 - <unknown>
   8:     0x7ff6f45aea33 - <unknown>
   9:     0x7ff6f44e8d09 - <unknown>
  10:     0x7ff6f44ef90a - <unknown>
  11:     0x7ff6f450634e - <unknown>
  12:     0x7ff6f4476e26 - <unknown>
  13:     0x7ff6f4506537 - <unknown>
  14:     0x7ff6f4cea240 - <unknown>
  15:     0x7ffa57027034 - BaseThreadInitThunk
  16:     0x7ffa573dd0d1 - RtlUserThreadStart
```

(I only wanted to paste an address. It works when I paste it using the mouse.)

**Comment by rajivshah3** [comment]
> Which makes me think that some mnemonic validation is missing?

Yep, that seemed to be the case. This should be fixed in iotaledger/wallet.rs#191

> when I press the Ctrl key on an interactive prompt, I get this

This looks similar to mitsuhiko/dialoguer#89 🤔

**Comment by lucasfernog** [comment]
The CLI wallet version 0.2.0 now uses stronghold so the env issues reported here are no longer relevant.

We'll keep an eye on the dialoguer issue when using CTRL :(

**Comment by schierlm** [comment]
As of 0.4.1, I still cannot press <kbd>Ctrl</kbd> (or even <kbd>Shift</kbd>) without getting dropped out of the interactive account menu
